### ISSUE TITLE
Bot wont add role

### ISSUE THREAD

**Issue by wewelimo** [restocked/Discord-Authentication-Bot#4]
i activate my key but it adds no role any help?

**Comment by washedpy** [comment]
You're probably using the wrong settings, make sure the server ID and the role name are correct.

**Comment by 35ulae** [comment]
Same here, it says "Missing Permissions" but Bot has Administrator & Manage Roles permission.

Log:

> (node:2148) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
>     at item.request.gen.end (/root/aktivacny-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
>     at then (/root/aktivacny-bot/node_modules/snekfetch/src/index.js:215:21)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:2148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:2148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 35ulae** [comment]
please help us:(

**Comment by washedpy** [comment]
Hey, DM me on Discord my username is Jimm¥#7777.
