### ISSUE TITLE
Role remove

### ISSUE THREAD

**Issue by saschawlt123** [restocked/Discord-Authentication-Bot#5]
Bot doesnt remove role after 30 days

**Comment by restocked** [comment]
Did you removed the token from the txt file?

**Comment by saschawlt123** [comment]
what token?

Von meinem iPhone gesendet

Am 01.02.2019 um 18:22 schrieb restocked <notifications@github.com<mailto:notifications@github.com>>:


Did you removed the token from the txt file?

**Comment by restocked** [comment]
Dm me on Discord please

**Comment by saschawlt123** [comment]
Whats your discord?

Von meinem iPhone gesendet

Am 01.02.2019 um 19:40 schrieb restocked <notifications@github.com<mailto:notifications@github.com>>:


Dm me on Discord please
